/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/medias/omnitrix.glb 
Author: AladdinDragonson (https://sketchfab.com/talonesping)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/os-omnitrix-live-action-style-fea6df3207974374a97e2264fb84dc7f
Title: OS Omnitrix Live Action Style
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/omnitrix.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 140.065, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[77.258, 77.258, 96.455]}>
          <mesh geometry={nodes.Circle001_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Circle001_GreenLight_1_0.geometry} material={materials.GreenLight_1} />
          <mesh geometry={nodes.Circle001_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Circle001_Eblem_Outline_0.geometry} material={materials.Eblem_Outline} />
          <mesh geometry={nodes.Circle001_Emblem_Sides_0.geometry} material={materials.Emblem_Sides} />
          <mesh geometry={nodes.Circle001_Button_Socket_0.geometry} material={materials.Button_Socket} />
          <mesh geometry={nodes.Circle001_Strap2001_0.geometry} material={materials['Strap2.001']} />
          <mesh geometry={nodes.Circle001_Strap_0.geometry} material={materials.Strap} />
          <mesh geometry={nodes.Circle001_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Circle001_Tubes_0.geometry} material={materials.Tubes} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/omnitrix.glb')
