/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Skull.glb --output components/Skull.js --transform 
Files: public/Skull.glb [164.96KB] > /Users/hassan/Documents/Personal Projects/Port/portfolio/components/Skull-transformed.glb [16.55KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Skull(props) {
  const { nodes, materials } = useGLTF('/Skull-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.face.geometry} material={nodes.face.material} position={[0, 0.737, 0]} scale={[0.785, 0.607, 0.785]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.clothes} position={[0, -0.266, 0]} scale={[0.23, 0.333, 0.454]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.skin} position={[0, -0.795, -0.569]} rotation={[0, -0.346, 0]} scale={[0.135, 0.115, 0.047]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.black} position={[0, -1.736, 0.247]} rotation={[0, -0.474, 0]} scale={[0.156, 0.091, 0.189]} />
      <mesh geometry={nodes.eyes001.geometry} material={materials.white} position={[0.733, 0.782, 0.418]} rotation={[0, 0.037, 0]} scale={[0.107, 0.107, 0.143]} />
    </group>
  )
}

useGLTF.preload('/Skull-transformed.glb')
